"""Task 1 deliverable: 'Free AI offers & services - how to claim'.

Merges the LIVE radar findings (data/airadar.db) with a curated baseline of
free AI services + claim methods, and writes:
  - D:\\scrapper\\docs\\free_ai_offers_2026-09-17.md   (repo doc)
  - D:\\scrapper\\data\\free_ai_offers.html           (standalone html)
"""
from __future__ import annotations

import html
import json
import sys
from pathlib import Path

sys.path.insert(0, r"D:\scrapper")
from airadar.store import Store  # noqa: E402

ROOT = Path(r"D:\scrapper")
DB = ROOT / "data" / "airadar.db"

FREE_TYPES = {"free_tier", "free_credits", "free_trial", "open_source", "giveaway"}
DIST_TYPES = {"lifetime_deal", "discount", "other"}

BASELINE = [
    ("Google AI Studio / Gemini API", "free_tier",
     "~1,500 requests/day, no credit card, Flash/Flash-Lite models.",
     "Open aistudio.google.com -> Get API key -> use the OpenAI-compatible endpoint. Enabling billing silently removes the free tier.",
     "https://ai.google.dev/gemini-api/docs/rate-limits"),
    ("Groq", "free_tier",
     "Free developer tier on LPU hardware (~30-60 RPM; no per-token charge, no card).",
     "Register at console.groq.com -> API Keys -> create key. Rate-limited, model access varies.",
     "https://console.groq.com"),
    ("Mistral La Plateforme", "free_tier",
     "Free 'Experiment' tier: rate-limited access to all models.",
     "Create an account at console.mistral.ai -> API keys. Roughly 1 request/second cap.",
     "https://console.mistral.ai"),
    ("OpenRouter free models", "free_tier",
     "Free-tier models (varies, ~14-25 at a time; e.g. Qwen/NVIDIA/Gemma variants).",
     "Sign up at openrouter.ai -> Keys -> filter models by ':free'. A one-off credit purchase unlocks higher free-model limits.",
     "https://openrouter.ai/docs/guides/routing/routers/free-router"),
    ("GitHub Models", "free_tier",
     "Free usage: high-tier models ~50 req/day (10/min), mini models ~150 req/day.",
     "Use a GitHub PAT against the Azure AI inference endpoint, or the playground at github.com/marketplace/models.",
     "https://github.com/marketplace/models"),
    ("Cerebras Inference", "free_credits",
     "One-off trial credit (~$5, ~30 days). No permanent free tier as of 2026.",
     "Sign up at cloud.cerebras.ai; a payment method is required for the trial.",
     "https://www.cerebras.ai"),
    ("NVIDIA Inception", "free_credits",
     "Free startup program: preferred GPU pricing, DGX Cloud discounts, cloud-credit bundles.",
     "Apply at nvidia.com/en-us/startups/ (company + website required).",
     "https://www.nvidia.com/en-us/startups/"),
    ("Startup credit stacks", "free_credits",
     "AWS Activate / Google for Startups / Microsoft for Startups + vendor programs (Anthropic, OpenAI, Mistral).",
     "Apply per program; most need a company entity and a pitch. Amounts and eligibility change often - verify before relying.",
     "https://creditforstartups.com/credits/ai"),
    ("Perplexity Pro (free routes)", "free_tier",
     "Free Pro access via partner bundles: telecom plans, Xfinity Rewards, student/education routes.",
     "Check your carrier/rewards program first; student verification gives a free month or discounted rate.",
     "https://www.perplexity.ai"),
    ("Student programs", "free_tier",
     "Gemini student offer, GitHub Student Developer Pack, education discounts on Claude/ChatGPT.",
     "Verify student status with the provider's academic partner (e.g. SheerID).",
     "https://education.github.com/pack"),
    ("Free-tier trackers (monitor these)", "other",
     "Pages that track free quotas continuously - the radar watches them via html_watch.",
     "costgoat.com, free-model.com, freellmapihub.com/programs/startups, pricepertoken.com.",
     "https://free-model.com/"),
]


def esc(s: str) -> str:
    return html.escape(s or "")


def main() -> int:
    store = Store(str(DB))
    stats = store.stats()
    offers = store.top_offers(limit=400)
    store.close()

    free = [o for o in offers if o.offer_type in FREE_TYPES]
    deals = [o for o in offers if o.offer_type in DIST_TYPES]
    withcode = [o for o in offers if o.promo_code]
    free.sort(key=lambda o: (-o.score, -len(o.items)))
    deals.sort(key=lambda o: (-o.score, -len(o.items)))

    # ---------- markdown (repo doc) ----------
    md = []
    md.append("# Free AI offers & services - how to claim")
    md.append("")
    md.append("Generated by AIOfferRadar's first live mission (2026-09-17). "
              "Part A is what the radar actually collected across platforms; "
              "Part B is a curated baseline of standing free services and claim methods.")
    md.append("")
    md.append(f"**Store:** {stats['items']} items, {stats['offers']} offers "
              f"({stats['offers_by_label']}); platforms: {stats['items_by_platform']}")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Part A - live radar findings (free offers)")
    md.append("")
    if not free:
        md.append("_No free-type offers in the current store._")
    for o in free[:40]:
        md.append(f"### [{o.label}] {o.title[:150] or o.product}")
        meta = [f"score {o.score:.0%}", f"`{o.offer_type}`"]
        if o.value:
            meta.append(f"**{o.value}**")
        if o.promo_code:
            meta.append(f"code `{o.promo_code}`")
        meta.append("platforms: " + ", ".join(o.platforms))
        md.append(" - ".join(meta))
        if o.url:
            md.append(f"<{o.url}>")
        for it in o.items[:3]:
            md.append(f"- {it.platform} @{it.author}: {(it.text or it.title)[:200]}"
                      + (f" ({it.url})" if it.url else ""))
        md.append("")
    md.append("## Part A2 - promo codes / deals found")
    md.append("")
    if not (withcode or deals):
        md.append("_None captured this cycle._")
    for o in (withcode + deals)[:25]:
        code = f" - code `{o.promo_code}`" if o.promo_code else ""
        md.append(f"- [{o.label}] {o.title[:120]}{code}"
                  + (f" <{o.url}>" if o.url else ""))
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Part B - standing free AI services & methods")
    md.append("")
    md.append("| Service | Type | What you get | How to claim | Source |")
    md.append("|---|---|---|---|---|")
    for name, t, what, how, url in BASELINE:
        md.append(f"| **{name}** | `{t}` | {what} | {how} | <{url}> |")
    md.append("")
    md.append("_Verify quotas before relying on them - free tiers change frequently._")
    (ROOT / "docs" / "free_ai_offers_2026-09-17.md").write_text(
        "\n".join(md) + "\n", encoding="utf-8")

    # ---------- html (delivery) ----------
    rows = []
    for o in free[:40]:
        rows.append(
            f'<article><h3>{esc(o.title[:160]) or esc(o.product)}</h3>'
            f'<p class="m"><span class="b">{esc(o.label)}</span> '
            f'<span class="s">{o.score:.0%}</span> <code>{esc(o.offer_type)}</code>'
            + (f' <b>{esc(o.value)}</b>' if o.value else "")
            + (f' <span class="code">code: {esc(o.promo_code)}</span>' if o.promo_code else "")
            + f' <span class="p">{esc(", ".join(o.platforms))}</span></p>'
            + (f'<p class="u"><a href="{esc(o.url)}">{esc(o.url)}</a></p>' if o.url else "")
            + "".join(f'<p class="src">{esc(i.platform)} @{esc(i.author)}: '
                      f'{esc((i.text or i.title)[:220])}</p>' for i in o.items[:3])
            + "</article>"
        )
    base_rows = "".join(
        f"<tr><td><b>{esc(n)}</b></td><td><code>{esc(t)}</code></td><td>{esc(w)}</td>"
        f"<td>{esc(h)}</td><td><a href='{esc(u)}'>{esc(u)}</a></td></tr>"
        for n, t, w, h, u in BASELINE
    )
    html_doc = f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Free AI offers &amp; services - how to claim</title><style>
:root{{--ink:#14181d;--mut:#6b7480;--line:#d8dde3;--paper:#fbfaf8;--acc:#8a1c1c;--ok:#1f6b45}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);
font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;line-height:1.6;
font-size:16px;-webkit-font-smoothing:antialiased}}
.page{{max-width:900px;margin:0 auto;padding:52px 26px 90px}}
.kick{{font-family:ui-monospace,Consolas,monospace;font-size:.7rem;letter-spacing:.15em;
text-transform:uppercase;color:var(--mut)}}
h1{{font-family:"Iowan Old Style",Georgia,serif;font-size:2.2rem;font-weight:600;
letter-spacing:-.015em;margin:10px 0 10px;line-height:1.15}}
h2{{font-family:"Iowan Old Style",Georgia,serif;font-size:1.3rem;margin:38px 0 12px;
padding-bottom:7px;border-bottom:1px solid var(--ink)}}
h3{{font-size:1rem;margin:20px 0 4px}}
article{{padding:12px 0;border-bottom:1px solid var(--line)}}
.m{{margin:2px 0;font-size:.84rem}}
.b{{font-weight:700;font-size:.7rem;letter-spacing:.06em}}
.s{{color:var(--acc);font-weight:700}}code{{font-family:ui-monospace,Consolas,monospace;
font-size:.8em;background:#eef1f4;border:1px solid var(--line);border-radius:3px;padding:.06em .3em}}
.code{{color:var(--acc);font-weight:600}}.p{{color:var(--mut);font-size:.78rem}}
.u a,.src a{{color:var(--acc);text-decoration:none}}.src{{color:var(--mut);font-size:.8rem;
margin:2px 0 0 12px}}
table{{width:100%;border-collapse:collapse;font-size:.86rem;margin-top:10px}}
th,td{{text-align:left;padding:7px 9px;border-bottom:1px solid var(--line);vertical-align:top}}
th{{font-family:ui-monospace,Consolas,monospace;font-size:.68rem;letter-spacing:.08em;
text-transform:uppercase;color:var(--mut);border-bottom:1px solid var(--ink)}}
footer{{margin-top:46px;padding-top:14px;border-top:1px solid var(--line);
font-family:ui-monospace,Consolas,monospace;font-size:.7rem;color:var(--mut)}}
</style></head><body><div class="page">
<div class="kick">AIOfferRadar - first live mission - 2026-09-17</div>
<h1>Free AI offers &amp; services: what exists and how to claim it</h1>
<p>Live scan: <b>{stats['items']}</b> items across <b>{len(stats['items_by_platform'])}</b> platforms
-&gt; <b>{stats['offers']}</b> offers (<b>{stats['offers_by_label']}</b>),
<b>{len(free)}</b> of them free-type.</p>
<h2>Part A - live findings: free offers</h2>
{''.join(rows) or '<p>No free-type offers in the store.</p>'}
<h2>Part B - standing free services &amp; claim methods</h2>
<table><thead><tr><th>Service</th><th>Type</th><th>What you get</th><th>How to claim</th><th>Source</th></tr></thead>
<tbody>{base_rows}</tbody></table>
<footer>Generated by AIOfferRadar (airadar) - verify quotas before relying on them.</footer>
</div></body></html>"""
    out = ROOT / "data" / "free_ai_offers.html"
    out.write_text(html_doc, encoding="utf-8")

    print("store:", json.dumps(stats))
    print("free offers:", len(free), "deals:", len(deals), "with promo code:", len(withcode))
    print("md  ->", ROOT / "docs" / "free_ai_offers_2026-09-17.md")
    print("html->", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
