"""Research driver over the You.com MCP (uses repo's own enricher).

Modes:
  balance   -> check YDC credit balance
  search    -> run the full query batch, save JSON + markdown digest
  contents  -> fetch page contents for URLs passed as args
"""
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, r"D:\scrapper")
from twitter_radar.enrich.youcom import YouComEnricher  # noqa: E402

KEY = ""
for line in open(r"D:\scrapper\secrets.env", encoding="utf-8"):
    line = line.strip()
    if line.startswith("YDC_API_KEY="):
        KEY = line.split("=", 1)[1].strip()
if not KEY:
    print("FATAL: YDC_API_KEY not found in secrets.env")
    sys.exit(2)

e = YouComEnricher(api_key=KEY, max_results=8, timeout=40)
OUT = Path(r"D:\scrapper\data\research_raw")
OUT.mkdir(parents=True, exist_ok=True)

QUERIES = [
    # platform access methods
    "Threads.net scraping public profile posts without login undocumented API 2026",
    "threads-python library github status working unofficial Threads API",
    "Instagram public profile JSON endpoint without login 2026 status",
    "instaloader public profile scraping without login rate limit 429",
    "gallery-dl Instagram public metadata no login",
    "YouTube channel RSS feed videos.xml channel_id fields without API key",
    "yt-dlp extract channel metadata flat playlist no authentication",
    "Reddit JSON API without OAuth blocked 403 datacenter IP User-Agent rules",
    "Reddit subreddit .rss feed alternative when json blocked",
    "Hacker News Algolia API search_by_date parameters tags numericFilters",
    "RSSHub routes instagram youtube reddit threads available instances",
    # where free AI offers surface
    "AppSumo AI tools lifetime deal RSS feed",
    "theresanaiforthat Futurepedia new AI tools feed RSS",
    "free AI credits startups 2026 cloud LLM API credits programs",
    "OpenAI Google Anthropic Mistral official blog RSS feed URL",
    "Perplexity AI changelog free Pro offers page",
    "AI tool giveaway lifetime deal aggregator websites 2026",
    "Reddit subreddits where free AI tool deals are posted",
]

mode = sys.argv[1] if len(sys.argv) > 1 else "balance"

if mode == "balance":
    resp = e._call("tools/call", {"name": "you-balance", "arguments": {}})
    print(json.dumps(resp, indent=2)[:2000])

elif mode == "search":
    all_results = {}
    for i, q in enumerate(QUERIES):
        res = e.search(q, max_results=8)
        all_results[q] = res
        print(f"[{i+1}/{len(QUERIES)}] {len(res):2d} hits | {q}")
        (OUT / f"search_{i:02d}.json").write_text(
            json.dumps({"query": q, "results": res}, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        time.sleep(1.0)
    (OUT / "all_searches.json").write_text(
        json.dumps(all_results, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    md = ["# Raw you-search digest (generated by scripts research driver)", ""]
    for q, res in all_results.items():
        md.append(f"## Q: {q}")
        if not res:
            md.append("- (no results)")
        for r in res:
            md.append(
                f"- [{(r.get('title') or '')[:110]}]({r.get('url','')}) "
                f"— {(r.get('description') or '')[:230]}"
            )
        md.append("")
    (OUT / "digest.md").write_text("\n".join(md), encoding="utf-8")
    print("digest ->", OUT / "digest.md")

elif mode == "contents":
    urls = sys.argv[2:]
    resp = e._call(
        "tools/call",
        {"name": "you-contents", "arguments": {"urls": urls, "formats": ["markdown"]}},
    )
    (OUT / "contents.json").write_text(
        json.dumps(resp, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    try:
        text = resp.get("result", {}).get("content", [{}])[0].get("text", "")
    except Exception:
        text = ""
    (OUT / "contents.md").write_text(text[:120000], encoding="utf-8")
    print(f"saved contents.md ({len(text)} chars)")

else:
    print(f"unknown mode {mode}")
    sys.exit(1)
